Repository Kirtar/react-shopping-cart-context, pull requests merged in 2021-06, with the labels that each got.

#16 Style/01 change navbar
  src/assets/img/zapato_veloz_logo.png
  src/components/AppHeader/AppHeader.js
  src/components/AppHeader/AppHeader.scss
Labels: enhancement

#18 Feat: create step 1 form component
  package.json
  src/CheckoutContext.js
  src/assets/img/france16.png
  src/assets/img/germany16.png
  src/assets/img/greece16.png
  src/assets/img/italy16.png
  src/assets/img/spain16.png
  src/assets/img/spain32.png
  src/components/CheckoutFooter/CheckoutFooter.js
  src/components/CheckoutFooter/CheckoutFooter.scss
  src/components/Input/Input.js
  src/components/StepOneForm/StepOne-schema.js
  src/components/StepOneForm/StepOneForm.js
  src/components/StepOneForm/StepOneForm.scss
  src/components/StepOneForm/index.js
Labels: New feature

#19 feat: create overview sidebar component
  src/components/CheckoutSidebar/CheckoutSidebar.js
  src/components/CheckoutSidebar/index.js
  src/components/ItemShowcase/ItemShowcase.js
  src/components/ItemShowcase/ItemShowcase.scss
  src/components/ItemShowcase/index.js
Labels: New feature

#20 feat: create step 2 form component
  src/CheckoutContext.js
  src/components/StepTwoForm/StepTwo-schema.js
  src/components/StepTwoForm/StepTwoForm.js
  src/components/StepTwoForm/index.js
Labels: New feature

#22 user's authentication management completed
  .eslintrc.js
  src/App.js
  src/components/AppHeader/AppHeader.js
  src/components/AuthContextProvider/AuthContextProvider.js
  src/components/Input/Input.js
  src/components/LoginForm/LoginForm.js
  src/components/LoginForm/index.js
  src/components/LogoutPanel/LogoutPanel.js
  src/components/LogoutPanel/index.js
  src/context/AuthContext.js
  src/pages/SignUp/SignUp.js
  src/pages/SignUp/SignUp.scss
  src/pages/SignUp/index.js
Labels: New feature

#25 Feat/04 create checkout page structure
  src/App.js
  src/CheckoutContext.js
  src/components/CheckoutSidebar/CheckoutSidebar.js
  src/components/Input/Input.js
  src/components/StepThreeForm/StepThreeForm.js
  src/hoc/checkoutLayout.js
  src/pages/CheckoutStepFour/CheckoutStepFour.js
  src/pages/CheckoutStepFour/index.js
  src/pages/CheckoutStepOne/CheckoutStepOne.js
  src/pages/CheckoutStepOne/index.js
  src/pages/CheckoutStepThree/CheckoutStepThree.js
  src/pages/CheckoutStepThree/index.js
  src/pages/CheckoutStepTwo/CheckoutStepTwo.js
  src/pages/CheckoutStepTwo/index.js
Labels: New feature

#27 feat: page nav created and implemented
  src/App.js
  src/components/Cart/Cart.js
  src/components/CheckoutFooter/CheckoutFooter.js
  src/components/StepOneForm/StepOneForm.js
  src/components/StepThreeForm/StepThreeForm.js
  src/components/StepTwoForm/StepTwoForm.js
Labels: New feature

#28 Feat/02 create checkout header component
  src/components/AuthContextProvider/index.js
  src/components/CheckoutHeader/CheckoutHeader.js
  src/components/CheckoutHeader/CheckoutHeader.scss
  src/components/CheckoutHeader/index.js
  src/hoc/checkoutLayout.js
Labels: New feature

#30 fix: Enhanced checkout fields performance and style
  src/CheckoutContext.js
  src/components/Cart/Cart.js
  src/components/CheckoutFooter/CheckoutFooter.js
  src/components/StepFourForm/StepFourForm.js
  src/components/StepOneForm/StepOneForm.js
  src/components/StepThreeForm/StepThree-schema.js
  src/components/StepThreeForm/StepThreeForm.js
  src/components/StepTwoForm/StepTwo-schema.js
  src/components/StepTwoForm/StepTwoForm.js
Labels: bug, enhancement
